export { normalizeEdge } from './normalizeEdge';
export { getCompanionEdge } from './getCompanionEdge';
export { getAdjacentSquare } from './getAdjacentSquare';
export { isWallBlocking } from './isWallBlocking';
export { getValidMoves, getDeflectedJumps } from './getValidMoves';
export type { DeflectedJump } from './getValidMoves';
export { wallsIntersect } from './wallsIntersect';
export { pathExists } from './pathExists';
export { isWallPlacementValid } from './isWallPlacementValid';
export { BOARD_SIZE, RED_START, RED_GOAL, BLUE_START, BLUE_GOAL } from './boardConfig';
export { createInitialState } from './createInitialState';
export { applyMove } from './applyMove';
export { applyWall } from './applyWall';
export { checkWinner } from './checkWinner';
export { getComputerMove } from './getComputerMove';
export type { ComputerAction, AiDifficulty } from './getComputerMove';
